# -*- coding: utf-8 -*-
"""Huggingface_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lktOIyPqdKuTliRw-pLxl6KtZpdC9y6j
"""

# ! pip install langchain-huggingface

from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
from dotenv import load_dotenv

load_dotenv()

model = HuggingFaceEndpoint(
    repo_id="deepseek-ai/DeepSeek-V3.2",
    task="text-generation"
)

chat_model = ChatHuggingFace(llm=model)

# response = chat_model.invoke("what is the capital of India?")
response = chat_model.invoke("Could you please write me a blog on generative ai, in 300 words?")

print(response.content)