# -*- coding: utf-8 -*-
"""huggingface_local_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdrqW8AH4eoZ1OCVGihPCbIhBGlDP0lF
"""

# ! pip install langchain-huggingface

from langchain_huggingface import ChatHuggingFace, HuggingFacePipeline

model = HuggingFacePipeline.from_model_id(
    model_id="TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    task="text-generation",
    pipeline_kwargs=dict(
        max_new_tokens=512,
        do_sample=False,
        repetition_penalty=1.03,
    ),
)

chat_model = ChatHuggingFace(llm=model)

response = chat_model.invoke("Could you please write me a blog on generative ai, in 300 words?")

print(response.content)